export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const CLEAN_INGREDIENTS = 'CLEAN_INGREDIENTS';

export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';

export const SET_DETAILS_INGREDIENT = 'SET_DETAILS_INGREDIENT';
export const CLEAN_DETAILS_INGREDIENT = 'CLEAR_DETAILS_INGREDIENT';

export const ADD_SELECTED_INGREDIENT = 'ADD_SELECTED_INGREDIENT';
export const DELETE_SELECTED_INGREDIENT = 'DELETE_SELECTED_INGREDIENT';
export const CLEAN_SELECTED_INGREDIENT = 'CLEAN_SELECTED_INGREDIENT';
export const UPDATE_SELECTED_INGREDIENTS = 'UPDATE_SELECTED_INGREDIENTS';

export const ORDER_REGISTRATION = 'ORDER_REGISTRATION';
export const ORDER_REGISTRATION_SUCCESS = 'ORDER_REGISTRATION_SUCCESS';
export const ORDER_REGISTRATION_FAILED = 'ORDER_REGISTRATION_FAILED';
export const ORDER_CLEAN = 'ORDER_CLEAN';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const RESET_AUTH = 'RESET_AUTH';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_AUTH = 'UPDATE_AUTH';